### PR TITLE
Add activeDeadlineSeconds to ClowdJob

### PR DESCRIPTION
**Pull request by kahowell**
This allows a couple of things:

1. A job can consume terminating quota by using activeDeadlineSeconds.
2. A job can use sidecars and use activeDeadlineSeconds to ensure the sidecars are eventually terminated.

Running the modified kuttl test:

```
kubectl kuttl test -v2 bundle/tests/scorecard/kuttl/ --test test-clowder-jobs
```

### CODE REVIEW

**Comment by psav** [comment]
Can you run `make api-docs` too on this please?

**Comment by kahowell** [comment]
b761fde to 87957a7: amend after running `make api-docs`.

@psav done

**Comment by kahowell** [comment]
87957a7 to 2398119: noticed a couple other generated docs that weren't picked up by `git commit -a` :smile:

**Comment by psav** [comment]
@kylape Are you able to review this?

**Review by kylape — APPROVED** [review]

**Pull request merged**
