### PR TITLE
Bumping Prometheus Operator version

### PR DESCRIPTION
**Pull request by gburges**

### CODE REVIEW

**Review by psav — CHANGES_REQUESTED** [review]
This won't affect the prometheus that is deployed - but should be done in tandem with updating the prometheus on the cluster right?

**Comment by gburges** [comment]
there's no prometheus deployed on the cluster - we removed it a while ago because it wasn't cleaning up properly

**Comment by psav** [comment]
> there's no prometheus deployed on the cluster - we removed it a while ago because it wasn't cleaning up properly

While we disabled the prometheus instances by default, the "operator" is still installed and at a much earlier version `0.56.3` _this_ is what needs updating first.....or in tandem with the update to the CRD spec in Clowder

**Review by psav — CHANGES_REQUESTED** [review]
Commented

**Comment by psav** [comment]
Is prometheus updated in the clusters now?

**Review by psav — COMMENTED** [review]
Is prometheus updated in the clusters now?

We should take a look at the version we deploy in the kubebuild script too

**Comment by adamrdrew** [comment]
We need to see that we have the correct operator versions deployed. Also, "We should take a look at the version we deploy in the kubebuild script too" from @psav can we get this looked at too?

**Comment by gburges** [comment]
> We need to see that we have the correct operator versions deployed. Also, "We should take a look at the version we deploy in the kubebuild script too" from @psav can we get this looked at too?

Looking. I would also propose to research user workload monitoring. This all could be moot if it works well for us

**Review by adamrdrew — APPROVED** [review]
LGTM

**Pull request merged**
