### PR TITLE
Install elasticsearch, xjoin-operator in kube_setup

### PR DESCRIPTION
**Pull request by fijshion**

### CODE REVIEW

**Comment by fijshion** [comment]
@kylape @bsquizz @psav

**Review by bsquizz — APPROVED** [review]
LGTM, I think Kyle and Pete are involved a little more directly in tinkering w/ this at the moment so will wait for their input too.

**Comment by psav** [comment]
I'm happy with it - but I'd like @kylape to chime in.

**Comment by fijshion** [comment]
@kylape anything stopping this from being merged?

**Review by kylape — APPROVED** [review]

**Comment by kylape** [comment]
Merge in a separate batch.

**Pull request closed without merging**
