### PR TITLE
add `minikube config` settings to readme

### PR DESCRIPTION
**Pull request by lindgrenj6**
Just adding some docs around persisting the flags that way they don't need to be remembered/referred. Can easily be tweaked as well.

### CODE REVIEW

**Comment by bsquizz** [comment]
Any idea if you can persist `--addons=registry` via the minikube config as well? That's the only other thing I'd suggest adding.

**Comment by lindgrenj6** [comment]
@bsquizz I haven't found a way to do that unfortunately, it's not possible to enable certain addons by default with `minikube config` yet. There are a few WIP PR's and issues adding the functionality though it looks like.

One option for that would be to run a registry somewhere, then config minikube with `minikube config set insecure-registry ip:port`, that basically configured the docker daemon to use an insecure registry. But that involves running the registry elsewhere which doesn't gain us much.

**Comment by bsquizz** [comment]
Yeah no worries, was just curious. I agree, the separate registry isn't worth it. `minikube --addons=registry` has been working well for me... and I don't have to ever check if some other VM/container/app is running so I like that ;)

**Comment by lindgrenj6** [comment]
100% same, having everything integrated is super nice.

**Comment by psav** [comment]
It's not passing I presume because of a lack of app-interface GPG? - plus it will need rebasing due to the kuttl update

**Pull request merged**
