### PR TITLE
[RHCLOUD-30831] - refactor(db): Remove Postgresql 10 support

### PR DESCRIPTION
**Pull request by Victoremepunto**

### CODE REVIEW

**Review by psav — CHANGES_REQUESTED** [review]
You also need to find and change this kubebuilder annotation line

```
	// +kubebuilder:validation:Enum:=10;12;13;14;15
```

**Comment by Victoremepunto** [comment]
> Still one test referencing version 10:
> 
> ```
> 10:48:23 [2024-03-26T10:48:23.157Z]     logger.go:42: 10:48:23 | test-multi-app-interface-db/1-pods | ClowdApp:test-multi-app-interface-db/app-e created
> 10:48:23 [2024-03-26T10:48:23.157Z]     case.go:364: failed in step 1-pods
> 10:48:23 [2024-03-26T10:48:23.157Z]     case.go:366: ClowdApp.cloud.redhat.com "app-default-ca" is invalid: spec.database.version: Unsupported value: 10: supported values: "12", "13", "14", "15", "16"
> 10:48:23 [2024-03-26T10:48:23.157Z]     case.go:366: ClowdApp.cloud.redhat.com "app-b" is invalid: spec.database.version: Unsupported value: 10: supported values: "12", "13", "14", "15", "16"
> 10:48:23 [2024-03-26T10:48:23.157Z]     case.go:366: ClowdApp.cloud.redhat.com "app-c" is invalid: spec.database.version: Unsupported value: 10: supported values: "12", "13", "14", "15", "16"
> 10:48:23 [2024-03-26T10:48:23.157Z]     case.go:366: ClowdApp.cloud.redhat.com "app-d" is invalid: spec.database.version: Unsupported value: 10: supported values: "12", "13", "14", "15", "16"
> ```

Thanks @bsquizz  !! fixed!

**Review by bsquizz — APPROVED** [review]

**Comment by Victoremepunto** [comment]
I think the Konflux pipeline may be fixed by #965

**Pull request merged**
