### PR TITLE
Add description to cyndiPipeline attributes

### PR DESCRIPTION
**Pull request by Victoremepunto**

### CODE REVIEW

**Review by adamrdrew — DISMISSED** [review]
Looks good for me

**Review by psav — CHANGES_REQUESTED** [review]
This should be changed in the comments in this file
`apis/cloud.redhat.com/v1alpha1/clowdapp_types.go`
and regenerated with `make pre-push`

**Comment by Victoremepunto** [comment]
> This should be changed in the comments in this file `apis/cloud.redhat.com/v1alpha1/clowdapp_types.go` and regenerated with `make pre-push`

so - should I commit all the files generated then ? I've pushed in a separate commit, feel free to squash if it's okay now

**Pull request merged**
