### PR TITLE
Set KafkaConnect override.policy to All

### PR DESCRIPTION
**Pull request by fijshion**
This is required to set this param in the Debezium connector: `producer.override.max.request.size: "2097152"`

### CODE REVIEW

**Review by bsquizz — APPROVED** [review]

**Comment by bsquizz** [comment]
I think the PR check is failing because the commit is not gpg signed

**Comment by fijshion** [comment]
I signed the commit and added my GPG key to github/app-interface. Not sure how to rerun the tests though.

**Comment by fijshion** [comment]
@bsquizz could you rerun the tests?

**Comment by fijshion** [comment]
@bsquizz could you take another look at this?

**Review by bsquizz — APPROVED** [review]

**Comment by bsquizz** [comment]
I'll leave it to @psav to merge because I know they are coordinating another prod push soon -- this seems pretty low risk though since its impacting only strimzi operator mode

**Comment by fijshion** [comment]
@psav please include this in the next release if you feel comfortable. This is blocking XJoin from working in the ephemeral clusters which is blocking HBI from performance testing for their new system profile filters.

**Review by kylape — APPROVED** [review]

**Comment by kylape** [comment]
Merged in a separate batch.

**Pull request closed without merging**
