### PR TITLE
[RHCLOUD-20320] Ephem managed kafka

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by adamrdrew** [comment]
FYI I'm working on a refactor of the managed-ephem provider code that I'll push up as a PR on this branch. It will add no new functionality - it'll simply reorg what's there. I started on it already, hopefully I can push up tonight or tomorrow.

**Comment by adamrdrew** [comment]
Alright, here's my proposal for a refactor: https://github.com/RedHatInsights/clowder/pull/672

Its gonna look pretty extreme at first - so much so that the diff view for looking at it basically useless because literally everything is moved around - but worry not! The refactor is only focused on organization, not logic. All of your logic should be exactly the same, but its been refactored into lots of little single purpose methods to make debugging, reasoning, and extension easier. 

Lets talk about it next week. Have a great weekend!

**Comment by adamrdrew** [comment]
Unfortunately I didn't get much done at all in the last 2 hours. I tried, but I ran into a mock dependency hell. Specifically, I hit a wall trying to implement a mock ObjectCache. We use a type rather than an interface for ObjectCache so I couldn't create a simple mock cache. Instead I'd have to create a legit ObjectCache and pass it mock dependencies, which means a mock client.Client - and after way too long searching I came up empty handed. I'm sorry - I'd hoped to have good test coverage at your start of day and unfortunately I have to drop now. I'll sync with you first thing AM my time and see how I can jump back in and help.

**Comment by adamrdrew** [comment]
Refactored to allow client mocking. Instead of http.Client in the code we now use a HTTPInterface. Client cache, the various mep methods etc deal with HTTPClient interfaces.

Where it gets tricky though is how we create clients. We don't create them directly, we use ` clientcredentials.Config` to do that. Sooooo the way we solve that is:

```golang
var ClientCreator func(provider *providers.Provider, clientCred clientcredentials.Config) HTTPClient

func init() {
	ClientCreator = func(provider *providers.Provider, clientCred clientcredentials.Config) HTTPClient {
		client := clientCred.Client(provider.Ctx)
		return client
	}
}
```

Sooo in our test code we:
```golang
type MockHTTPClient struct {
}

func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	return nil, nil
}
func (m *MockHTTPClient) Get(url string) (resp *http.Response, err error) {
	return nil, nil
}
func (m *MockHTTPClient) Post(url, contentType string, body io.Reader) (resp *http.Response, err error) {
	return nil, nil
}

func init() {
	ClientCreator = func(provider *providers.Provider, clientCred clientcredentials.Config) HTTPClient {
		return &MockHTTPClient{}
	}
}

```

Bada bing, bada boom as they say.

So this should get us to being able to mock out our HTTP client requests with whatever we want them to do. We'll still need to implement the testenv harness for getting the object cache etc going.

**Comment by adamrdrew** [comment]
Uh, I'm not sure what Jenkins is smoking:

```
15:31:37 go fmt ./...
15:31:37 go vet ./...
15:31:42 # github.com/RedHatInsights/clowder/controllers/cloud.redhat.com/providers/kafka
15:31:42 controllers/cloud.redhat.com/providers/kafka/managed-ephem.go:387:28: too many arguments in call to createCyndiPipeline
15:31:42 	have (context.Context, client.Client, *resource_cache.ObjectCache, *"github.com/RedHatInsights/clowder/apis/cloud.redhat.com/v1alpha1".ClowdApp, *"github.com/RedHatInsights/clowder/apis/cloud.redhat.com/v1alpha1".ClowdEnvironment, string, string)
15:31:42 	want (providers.RootProvider, *"github.com/RedHatInsights/clowder/apis/cloud.redhat.com/v1alpha1".ClowdApp, string, string)
15:31:42 # github.com/RedHatInsights/clowder/controllers/cloud.redhat.com/providers/kafka
15:31:42 vet: controllers/cloud.redhat.com/providers/kafka/managed-ephem.go:388:40: too many arguments in call to createCyndiPipeline
15:31:42 make: *** [vet] Error 2
```
That's bogus. On my machine:
```
$ [15:35] adamdrew @ adamwork: ~/Development/clowder [psav/ephem_managed_kafka]: Untracked
$ go fmt ./... ; go vet ./...
[15:37] adamdrew @ adamwork: ~/Development/clowder [psav/ephem_managed_kafka]: Untracked
$ 
```

I've never seen that before. Can't reproduce locally. I'll ask around.

**Comment by bsquizz** [comment]
`go vet` on this branch works locally for me too. One theory: Is Jenkins running the tests against this branch after it has been merged into/rebased against master?

**Pull request merged**
