### PR TITLE
Rename minkube_setup.sh to strimzi_install.sh

### PR DESCRIPTION
**Pull request by kylape**
afiact this has nothing to do with minikube

### CODE REVIEW

**Comment by psav** [comment]
@bsquizz do we need to update another script here?

**Comment by bsquizz** [comment]
Technically this script is going to become the script that "prepares your local k8s cluster" -- whatever that might involve.

In #214 the script is now installing both strimzi and prometheus operator

**Comment by bsquizz** [comment]
I'd close this and just address the rename in #214 -- because I have other scripts there calling this one now.

**Pull request closed without merging**
