### PR TITLE
Add check for commit message length

### PR DESCRIPTION
**Pull request by kylape**
This should also catch the formatting mistake where the second line is
not left blank.

### CODE REVIEW

**Comment by kylape** [comment]
based on https://stackoverflow.com/a/34664075

**Comment by psav** [comment]
How does this catch the second line not being blank?

**Review by psav — COMMENTED** [review]
I'm not sure I see how this protects the second line not being blank

**Comment by kylape** [comment]
`git log --pretty=format:%s` prints the subject line from each commit message.  If there is no blank line, it will concatenate all the lines together into one lone line.

**Comment by psav** [comment]
So you're banking on the fact that the summary and second line combined will break the line length?

**Comment by kylape** [comment]
Yes.

**Comment by kylape** [comment]
It's admittedly a "cheap" solution.

**Pull request merged**
