### PR TITLE
Switch out the envoy reverse proxy for caddy

### PR DESCRIPTION
**Pull request by SteveHNH**
Envoy dropped support for the only version that will run on RHEL8 and no longer does security patches. This impacts secure environments since we can't use later images for envoy. Instead, we can swap out for caddy which effectively does the same thing

[RHCLOUD-29123](https://issues.redhat.com/browse/RHCLOUD-29123)

### CODE REVIEW

**Comment by SteveHNH** [comment]
looks like this failing test is due to a `wget` to feature flags getting a 404. Not sure the solution to that just yet

**Review by psav — CHANGES_REQUESTED** [review]
Happy to make these changes if you're too busy on return - just let me know

**Pull request merged**
