### PR TITLE
WIP: Add deployment label to svc resource

### PR DESCRIPTION
**Pull request by kylape**

### CODE REVIEW

**Comment by psav** [comment]
This is failing because you have set the "apps" services to receive the new labels, but not the individual provider services.

**Comment by psav** [comment]
Let me know if you want me to fix it up

**Comment by kylape** [comment]
@psav we don't want other provider Services to have this label, do we?

**Comment by psav** [comment]
I'm not sure - I forget what the label was for - regardless - it probably needs a rebase to pass tests

**Pull request closed without merging**
